# Generated by Django 5.1.7 on 2025-03-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('cedula', models.BigIntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('celular', models.BigIntegerField(blank=True, null=True, verbose_name='Celular')),
                ('ruta', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre de la ruta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
