# Generated by Django 5.1.7 on 2025-03-13 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuotaspactadas', models.IntegerField(verbose_name='Cuotas pactadas')),
                ('intereses', models.IntegerField()),
                ('valorcredito', models.BigIntegerField()),
                ('valorprestado', models.BigIntegerField()),
                ('formapago', models.CharField(choices=[('MENSUAL', 'Mensual'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('DIARIO', 'Diario')], max_length=50, verbose_name='Forma de pago')),
                ('cuotaactual', models.IntegerField()),
                ('abono', models.IntegerField(blank=True, default=0, null=True)),
                ('saldopendiente', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_prestamos.cliente')),
            ],
        ),
    ]
