# Generated by Django 5.1.7 on 2025-03-13 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0002_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cuotaactual',
            field=models.IntegerField(verbose_name='Cuota actual'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='saldopendiente',
            field=models.BigIntegerField(verbose_name='Saldo pendiente'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='valorcredito',
            field=models.BigIntegerField(editable=False, verbose_name='Valor del credito'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='valorprestado',
            field=models.BigIntegerField(verbose_name='Valor prestado'),
        ),
        migrations.CreateModel(
            name='HistorialAbono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(verbose_name='Monto del abono')),
                ('fecha_abono', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='gestion_prestamos.prestamo')),
            ],
        ),
    ]
