# Generated by Django 5.1.7 on 2025-03-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0003_alter_prestamo_cuotaactual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialabono',
            name='saldo_pendiente',
            field=models.BigIntegerField(default=1, verbose_name='Saldo pendiente después del abono'),
            preserve_default=False,
        ),
    ]
